#:schema node_modules/@opennextjs/cloudflare/schema.json
name = "nezha-dash"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[observability]
enabled = true
